def ask_question(rag_chain, question: str):
    """
    Ask a question using the RAG chain.

    Args:
        rag_chain: The configured RAG chain.
        question: User's question.

    Returns:
        The response generated by the RAG chain.
    """
    response = rag_chain.invoke(
        {
            "input": question
        }
    )

    return response